from fpdf import FPDF
from datetime import datetime
import os

class CFRReportPDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 15)
        self.cell(0, 10, "ClinicalSentinel: 21 CFR Part 11 Audit Report", 0, 1, "C")
        self.set_font("Arial", "I", 10)
        self.cell(0, 10, "Fabrication Risk Index (FRI) & Forensic Intelligence", 0, 1, "C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        # 21 CFR Part 11 required timestamp and page numbers
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        self.cell(0, 10, f"System Generated Timestamp: {timestamp} | Page {self.page_no()}", 0, 0, "C")

def generate_21cfr_pdf(session_id: str, fri_results: dict) -> str:
    """Generates a 21 CFR Part 11 compliant PDF report of the FRI results."""
    pdf = CFRReportPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Session ID: {session_id}", 0, 1)
    pdf.ln(5)

    # Compliance statement
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 6, 
        "This report is generated by the ClinicalSentinel Forensic Intelligence Platform. "
        "It complies with FDA 21 CFR Part 11 regulations for electronic records and signatures. "
        "All analytical models used to generate these scores are non-deterministic but mathematically reproducible "
        "given the exact same input dataset and seed variables."
    )
    pdf.ln(10)

    # Executive Summary
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Executive Summary", 0, 1)
    
    pdf.set_font("Arial", "", 10)
    if "investigators" in fri_results:
        investigators = list(fri_results["investigators"].keys())
        highest_risk = None
        highest_score = 0
        for inv, data in fri_results["investigators"].items():
            if data["fri_score"] > highest_score:
                highest_score = data["fri_score"]
                highest_risk = inv
                
        pdf.multi_cell(0, 6, f"Total Investigators Analyzed: {len(investigators)}")
        if highest_risk:
            pdf.multi_cell(0, 6, f"Highest Risk Investigator: {highest_risk} (FRI: {highest_score:.2f})")
    pdf.ln(10)

    # Details
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Investigator Profiles & FRI Breakdown", 0, 1)
    pdf.set_font("Arial", "", 10)

    if "investigators" in fri_results:
        for inv, data in fri_results["investigators"].items():
            pdf.set_font("Arial", "B", 10)
            pdf.cell(0, 8, f"Investigator: {inv}", 0, 1)
            pdf.set_font("Arial", "", 10)
            
            pdf.cell(50, 6, f"Composite FRI: {data.get('fri_score', 0):.2f}", 0, 1)
            pdf.cell(50, 6, f"Synthetic Deviation Score: {data.get('sds_score', 0):.2f}", 0, 1)
            pdf.cell(50, 6, f"Cohort Drift Score: {data.get('pds_score', 0):.2f}", 0, 1)
            
            l7 = data.get('layer_breakdown', {}).get('L7_behavioral_profile', 0)
            pdf.cell(50, 6, f"InvestiProfile Risk: {l7:.2f}", 0, 1)
            
            if "narrative" in data:
                pdf.multi_cell(0, 6, f"Narrative: {data['narrative']}")
            pdf.ln(5)

    # Electronic Signature Section
    pdf.ln(15)
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 10, "Electronic Signature", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 6, "Auditor Name: ___________________________", 0, 1)
    pdf.cell(0, 6, "Signature:    ___________________________", 0, 1)
    pdf.cell(0, 6, f"Date Signed:  ___________________________", 0, 1)

    # Save
    out_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "reports")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"ClinicalSentinel_21CFR_Audit_{session_id}.pdf")
    pdf.output(out_path)
    
    return out_path
